### ISSUE TITLE
EPIC: Internal Evaluation Module

### ISSUE THREAD

**Issue by NilHomedes** [AjuntamentdeBarcelona/internal-evaluation-module#1]
This EPIC consist in the creation of a new module called "Internal Evaluation" that would allow managing in an easier way the internal evaluation process of a proposal. 

- [ ] - [ ] DIT22-1 New feature: internal evaluation #2 
- [ ] DIT22-4 Differentiate between the proposals I have already evaluated and those pending #3 
- [ ] DIT 22-6 Change evaluators column in admin proposals list #4 
- [ ] DIT22-8 Allow exporting internal evaluations #5
